services:

  postgres:
    image: 'postgres:16.2@sha256:6b841c8f6a819884207402f1209a8116844365df15fca8cf556fc54a24c70800'
    ports:
      - "5432:5432"
    environment:
      PGHOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
      POSTGRES_DB: tomorrow
    volumes:
      - "${PWD}/scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql"
      - "pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 20s
      retries: 20

  tomorrow:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m tomorrow
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: tomorrow
      TOMORROW: qxBfoHFh9LIV7yRhVA92yB3EqC7eBu98
    volumes:
      - "${PWD}/blobs:/tmp/blobs"
    depends_on:
      postgres:
        condition: service_healthy

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    command: jupyter notebook --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password='' --allow-root
    ports:
      - "8888:8888"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: tomorrow
    volumes:
      - "${PWD}/analysis.ipynb:/app/analysis.ipynb"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata:
